site_name: QoA4ML Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - QoA4ML: index.md
  - Code Reference: reference/

plugins:
  - social
  - search
  - section-index
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            allow_inspection: false
            show_bases: false
            find_stubs_package: true
            parameter_headings: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_category_heading: true
            show_object_full_path: false
            show_root_members_full_path: false
            show_root_heading: true
            docstring_style: numpy

          import:
            - https://docs.python-requests.org/en/master/objects.inv

markdown_extensions:
  toc:
    permalink: true
  markdown.extensions.codehilite:
    guess_lang: false
  admonition: null
  codehilite: null
  extra: null
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ""
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.tilde: null
  attr_list: null
  md_in_html: null

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rdsea

    - icon: /material/mailbox
      name: contact us
      link: https://rdsea.github.io/

copyright: |
  &copy; 2024 <a href="https://github.com/rdsea"  target="_blank" rel="noopener">Rdsea</a>
