from pydantic import BaseModel, Field, model_validator

from ..lang.datamodel_enum import (
    EnvironmentEnum,
    MetricClassEnum,
    MetricNameEnum,
    ServiceAPIEnum,
)


class ClientInfo(BaseModel):
    """Identity and metadata for a QoA client instance."""

    id: str = Field(
        default="",
        description="The id of the QoAClient, should be not be set manually, auto-generated by QoAClient",
    )
    name: str = Field(
        default="",
        description="The name of the QoAClient, for example, qoa_client1",
    )

    user_id: str = Field(
        default="",
        description="Can be set if you have external user_id, otherwise auto generated",
    )
    username: str = Field(default="", description="The name of the qoa_client user")
    instance_id: str = Field(
        default="",
        description="An UUID4 that is used to identify the instance, can be set manually in the config or through environment variable INSTANCE_ID, if not, auto-generated by QoAClient",
    )
    instance_name: str = Field(default="", description="The name of the instance")
    stage_id: str = Field(
        default="",
        description="Identifier for the pipeline stage this client belongs to",
    )
    functionality: str = Field(
        default="",
        description="Describes the functionality or role of this client in the pipeline",
    )
    application_name: str = Field(
        default="", description="Name of the application this client is part of"
    )
    role: str = Field(
        default="", description="Role of this client, e.g. 'producer' or 'consumer'"
    )
    run_id: str = Field(
        default="", description="Identifier for the current run or experiment"
    )
    environment: EnvironmentEnum = Field(
        default=EnvironmentEnum.edge,
        description="The environment where the qoa_client is run",
    )
    custom_info: dict | str = Field(
        default="", description="Additional information that you can add"
    )
    logging_level: int = Field(
        default=2,
        description="""Change logging level
        The desired logging level:
        0 - NOTSET
        1 - DEBUG
        2 - INFO
        3 - WARNING
        4 - ERROR
        5 - CRITICAL
        """,
    )


class AMQPCollectorConfig(BaseModel):
    """Configuration for collecting messages from an AMQP (RabbitMQ) broker."""

    end_point: str = Field(description="RabbitMQ server hostname or AMQPS URL")
    exchange_name: str = Field(description="Name of the exchange to consume from")
    exchange_type: str = Field(
        description="Exchange type, e.g. 'topic', 'direct', or 'fanout'"
    )
    in_routing_key: str = Field(
        description="Routing key pattern used to bind the queue to the exchange"
    )
    in_queue: str = Field(description="Name of the queue to consume messages from")


class AMQPConnectorConfig(BaseModel):
    """Configuration for connecting to an AMQP (RabbitMQ) message broker."""

    end_point: str = Field(description="RabbitMQ server hostname or AMQPS URL")
    exchange_name: str = Field(description="Name of the exchange to publish to")
    exchange_type: str = Field(
        description="Exchange type, e.g. 'topic', 'direct', or 'fanout'"
    )
    out_routing_key: str = Field(
        description="Routing key used when publishing messages"
    )
    health_check_disable: bool = Field(
        default=False,
        description="If True, disable periodic health checks on the AMQP connection",
    )


class MQTTConnectorConfig(BaseModel):
    """Configuration for connecting to an MQTT broker."""

    in_queue: str = Field(
        description="MQTT topic to subscribe to for incoming messages"
    )
    out_queue: str = Field(description="MQTT topic to publish outgoing messages to")
    broker_url: str = Field(description="MQTT broker URL, e.g. 'mqtt://localhost'")
    broker_port: int = Field(description="Port number of the MQTT broker, e.g. 1883")
    broker_keepalive: int = Field(
        description="Keep-alive interval in seconds for the MQTT connection"
    )
    client_id: str = Field(description="Unique client identifier for the MQTT session")


class SocketConnectorConfig(BaseModel):
    """Configuration for a TCP socket connector."""

    host: str = Field(description="Hostname or IP address to connect to")
    port: int = Field(description="Port number to connect to")


class SocketCollectorConfig(BaseModel):
    """Configuration for a TCP socket collector (server)."""

    host: str = Field(description="Hostname or IP address to bind the server socket to")
    port: int = Field(description="Port number to listen on")
    backlog: int = Field(
        description="Maximum number of queued connections for the listening socket"
    )
    bufsize: int = Field(description="Buffer size in bytes for receiving data")


class PrometheusConnectorConfig(BaseModel):
    """Configuration for a Prometheus metrics connector. Currently has no fields."""

    pass


class KafkaConnectorConfig(BaseModel):
    """Configuration for publishing messages to a Kafka broker."""

    topic: str = Field(description="Kafka topic to publish messages to")
    broker_url: str = Field(description="Kafka broker URL, e.g. 'localhost:9092'")


class KafkaCollectorConfig(BaseModel):
    """Configuration for consuming messages from a Kafka broker."""

    topic: str = Field(description="Kafka topic to consume messages from")
    broker_url: str = Field(description="Kafka broker URL, e.g. 'localhost:9092'")
    group_id: str = Field(description="Consumer group ID for coordinated consumption")
    auto_offset_reset: str = Field(
        default="earliest",
        description="Where to start reading when no committed offset exists: 'earliest' or 'latest'",
    )
    poll_interval: float = Field(
        default=1.0,
        description="Polling interval in seconds between consumer fetch requests",
    )


class DebugConnectorConfig(BaseModel):
    """Configuration for a debug connector used in development and testing."""

    silence: bool = Field(
        description="If True, suppress all output from the debug connector"
    )


CollectorConfigClass = (
    AMQPCollectorConfig | SocketCollectorConfig | KafkaCollectorConfig | dict
)
ConnectorConfigClass = (
    AMQPConnectorConfig
    | SocketConnectorConfig
    | KafkaConnectorConfig
    | DebugConnectorConfig
    | dict
)


class CollectorConfig(BaseModel):
    """Wrapper that pairs a collector implementation class with its specific configuration."""

    name: str = Field(description="Human-readable name for this collector instance")
    collector_class: ServiceAPIEnum = Field(
        description="The type of collector to use, e.g. 'amqp', 'socket', or 'kafka'"
    )
    config: CollectorConfigClass = Field(
        description="Implementation-specific configuration for the chosen collector class"
    )


class ConnectorConfig(BaseModel):
    """Wrapper that pairs a connector implementation class with its specific configuration."""

    name: str = Field(description="Human-readable name for this connector instance")
    connector_class: ServiceAPIEnum = Field(
        description="The type of connector to use, e.g. 'amqp', 'rest', 'kafka', or 'debug'"
    )
    config: ConnectorConfigClass | None = Field(
        default=None,
        description="Implementation-specific configuration for the chosen connector class, or None for connectors that need no extra config",
    )


class ClientConfig(BaseModel):
    """Top-level configuration that fully describes a QoA client and its connectors, collectors, and probes."""

    client: ClientInfo = Field(description="Identity and metadata for this client")
    registration_url: str | None = Field(
        default=None,
        description="URL of the registration service; if set, the client will register itself on startup",
    )
    collector: list[CollectorConfig] | None = Field(
        default=None,
        description="List of collector configurations for ingesting messages",
    )
    connector: list[ConnectorConfig] | None = Field(
        default=None,
        description="List of connector configurations for publishing reports",
    )
    probes: list["ProbeConfig"] | None = Field(
        default=None,
        description="List of probe configurations for monitoring system or process metrics",
    )

    @model_validator(mode="before")
    @classmethod
    def validate_probe_type(cls, values):
        probe_type_map: dict[str, type[ProbeConfig]] = {
            "process": ProcessProbeConfig,
            "docker": DockerProbeConfig,
            "system": SystemProbeConfig,
        }
        probes = values.get("probes", [])
        if probes:
            for i, probe_data in enumerate(probes):
                probe_type = probe_data.get("probe_type")
                if probe_type in probe_type_map:
                    probes[i] = probe_type_map[probe_type](**probe_data)
            values["probes"] = probes
        return values


class MetricConfig(BaseModel):
    """Configuration for an individual QoA metric."""

    name: MetricNameEnum = Field(
        description="Metric name identifier from the MetricNameEnum"
    )
    metric_class: MetricClassEnum = Field(
        description="Class of metric, e.g. gauge, counter, or histogram"
    )
    description: str | None = Field(
        default=None, description="Optional human-readable description of the metric"
    )
    default_value: int = Field(description="Initial or fallback value for the metric")
    category: int = Field(
        description="Numeric category used to group related metrics together"
    )


class GroupMetricConfig(BaseModel):
    """Configuration for a named group of related metrics."""

    name: str = Field(description="Name of the metric group")
    metric_configs: list[MetricConfig] = Field(
        description="List of individual metric configurations in this group"
    )


class ProbeConfig(BaseModel):
    """Base configuration shared by all probe types."""

    probe_type: str = Field(
        description="Type of probe, e.g. 'process', 'system', 'docker', or 'jetson_sys'"
    )
    frequency: int = Field(description="Data collection frequency in seconds")
    require_register: bool = Field(
        description="Whether the probe must register with the observation service before reporting"
    )
    obs_service_url: str | None = Field(
        default=None,
        description="URL of the observation service for probe registration",
    )
    log_latency_flag: bool = Field(
        description="If True, record and log the latency of each probe report"
    )
    latency_logging_path: str | None = Field(
        default=None,
        description="File path for writing latency logs; used only when log_latency_flag is True",
    )
    environment: EnvironmentEnum = Field(
        default=EnvironmentEnum.edge, description="The environment where the probe run"
    )


class ProcessProbeConfig(ProbeConfig):
    """Probe configuration for monitoring a specific OS process."""

    probe_type: str = Field(
        default="process", description="Fixed probe type identifier for process probes"
    )
    pid: int | None = Field(
        default=None,
        description="Process ID to monitor; if None, monitors the current process",
    )


class SystemProbeConfig(ProbeConfig):
    """Probe configuration for monitoring system-level resources (CPU, memory, etc.)."""

    probe_type: str = Field(
        default="system", description="Fixed probe type identifier for system probes"
    )
    node_name: str | None = Field(
        default=None, description="Human-readable name of the node being monitored"
    )


class DockerProbeConfig(ProbeConfig):
    """Probe configuration for monitoring Docker containers."""

    probe_type: str = Field(
        default="docker", description="Fixed probe type identifier for Docker probes"
    )
    container_list: list[str] = Field(
        default=[],
        description="List of container names or IDs to monitor; empty means monitor all",
    )


class JetsonSystemProbeConfig(ProbeConfig):
    """Probe configuration for monitoring NVIDIA Jetson system-level metrics."""

    probe_type: str = Field(
        default="jetson_sys",
        description="Fixed probe type identifier for Jetson system probes",
    )
    node_name: str | None = Field(
        description="Human-readable name of the Jetson node being monitored"
    )


class JetsonProcessesProbeConfig(ProbeConfig):
    """Probe configuration for monitoring processes on an NVIDIA Jetson device."""

    probe_type: str = Field(
        default="jetson_sys",
        description="Fixed probe type identifier for Jetson process probes",
    )
    node_name: str | None = Field(
        description="Human-readable name of the Jetson node being monitored"
    )


ClientConfig.model_rebuild()


class NodeAggregatorConfig(BaseModel):
    """Configuration for aggregating metrics from edge or cluster nodes."""

    socket_collector_config: SocketCollectorConfig = Field(
        description="Socket collector settings used to receive data from nodes"
    )
    environment: EnvironmentEnum = Field(
        description="Deployment environment for the aggregator, e.g. edge or cloud"
    )
    query_method: str = Field(
        description="Method used to obtain data from nodes, e.g. 'pull' or 'push'"
    )
    data_separator: str = Field(
        description="Character used to separate fields in incoming data, e.g. ','"
    )
    unit_conversion: dict = Field(
        description="Mapping of source units to target units for metric normalization"
    )


class ExporterConfig(BaseModel):
    """Configuration for exporting aggregated metrics via an HTTP endpoint."""

    host: str = Field(description="Hostname or IP address to bind the exporter to")
    port: int = Field(description="Port number for the exporter HTTP server")
    node_aggregator: NodeAggregatorConfig = Field(
        description="Node aggregator configuration used by the exporter"
    )


class OdopObsConfig(BaseModel):
    """Configuration for the ODOP observation system combining process, system, and exporter settings."""

    process: ProcessProbeConfig = Field(
        description="Process probe configuration for monitoring application processes"
    )
    system: SystemProbeConfig = Field(
        description="System probe configuration for monitoring host-level resources"
    )
    probe_connector: SocketConnectorConfig = Field(
        description="Socket connector used by probes to send collected data"
    )
    exporter: ExporterConfig = Field(
        description="Exporter configuration for serving aggregated metrics"
    )
