name: Python CI

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd qoa4ml_lib
        pip install -r requirements.txt
        pip install -r dev_requirements.txt
        # Uncomment when fix ydata
        #pip install -r ml_requirements.txt
        cd ..
    - uses: pre-commit/action@v3.0.1
